from typing import Optional, Tuple


class Machine(object):
    def __init__(self, input: Optional[str] = None, code: Optional[str] = None): ...
    def exec_op(self, opcode: int): ...
    def has_loaded(self) -> bool: ...
    def is_end(self) -> bool: ...
    def load_file(self, filename: str): ...
    def load_input(self, inp: str): ...
    def load_str(self, code: str): ...
    def next_op(self) -> int: ...
    def peek(self) -> int: ...
    def step(self) -> Optional[Tuple[int, int]]: ...
